training:
  batch_size: 128
  n_epochs: 3000
  n_iters: 100000
  algo: "vae"

data:
  dataset: "MNIST"
  image_size: 28
  channels: 1

model:
  z_dim: 8
  eps_dim: 8
  nef: 16
  ndf: 16
  n_particles: 1

optim:
  weight_decay: 0.000
  optimizer: "RMSProp"
  lr: 0.0001
